
context('E2E tseting for spotify searcher', () => {
  it('display home page as expected', () => {
    cy.visit('http://localhost:3000')
    cy.get('.logo').should('be.visible')
    cy.get('.logo img').should('be.visible')
    cy.get('.search-container').should('be.visible')
    cy.get('.searchField').should('be.visible')
    cy.get('.search-container button').should('be.visible')
    cy.wait(1000)
    cy.get('.genre-container').should('be.visible')
    cy.get('.genre-container .genre').should('be.visible')
    cy.get('.genre-container .genre p').should('be.visible')
    cy.get('.genre-container .genre img').should('be.visible')
  })
  it('should display the categories playlist', () => {
    cy.get('.genre-container .genre').eq(0).click({ force: true })
    cy.get('.playlist-container').should('be.visible')
    cy.get('.playlist-container .playlist').should('be.visible')
    cy.get('.playlist-container .playlist p').should('be.visible')
    cy.get('.playlist-container .playlist img').should('be.visible')
  })
  it('should perform a search', () => {
    cy.wait(500)
    cy.get('.logo')
      .click({ force: true })
    cy.get('.searchField')
      .type('twenty')
      .should('have.value', 'twenty')
    cy.get('.search-container button')
      .click({ force: true })
  })
  it('filters work as expected', () => { 
    cy.wait(1000)
    cy.get('.filter-container').should('be.visible')
    cy.get('.filter-order').should('be.visible')
    cy.get('.filter-order p').should('be.visible')
    cy.get('.filter-order p').should('contain', 'Order By')
    cy.get('.filter-container button').should('have.length', 2)
    cy.get('.filter-container button').eq(0)
      .click({ force: true })
    cy.wait(200)
    cy.get('.filter-container button').eq(1)
      .click({ force: true })
   cy.wait(200)
  })
  it('search a new querie', () => {
    cy.wait(500)
    cy.get('.searchField')
      .clear()
      .type('metallica')
      .should('have.value', 'metallica')
      .type('{enter}')
  })
})
